'use client'
import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import api from '@/lib/api'
interface Room { name: string; capacity: number; price: number; description: string }
interface FormData { hotelName: string; address: string; phone: string; contactName: string; email: string; description: string; rooms: Room[]; checkin: string; checkout: string; pets: string; smoking: string; wifi: boolean; parking: boolean; pool: boolean; restaurant: boolean; transfer: boolean; breakfast: boolean; communicationStyle: string }
const defaultForm: FormData = { hotelName: '', address: '', phone: '', contactName: '', email: '', description: '', rooms: [{ name: '', capacity: 2, price: 0, description: '' }], checkin: '14:00', checkout: '12:00', pets: 'no', smoking: 'no', wifi: true, parking: false, pool: false, restaurant: false, transfer: false, breakfast: false, communicationStyle: 'friendly' }
const demoForm: FormData = { hotelName: 'Ton Azure', address: 'с. Тон, Иссык-Куль', phone: '+996 555 123 456', contactName: 'Бектур', email: 'tonazure@mail.com', description: 'Бутик-отель на берегу Иссык-Куля. 12 номеров, ресторан, пляж, зона барбекю.', rooms: [ { name: 'Twin Standard', capacity: 2, price: 4500, description: 'Две раздельные кровати, душ, ТВ, Wi-Fi' }, { name: 'Double Comfort', capacity: 2, price: 5500, description: 'Одна большая кровать, балкон с видом на озеро' }, { name: 'Family Suite', capacity: 4, price: 8500, description: 'Две комнаты, кухня, балкон' }, ], checkin: '14:00', checkout: '12:00', pets: 'no', smoking: 'balcony', wifi: true, parking: true, pool: false, restaurant: true, transfer: true, breakfast: true, communicationStyle: 'friendly' }
export default function CreateBotPage() {
  const router = useRouter()
  const [authChecked, setAuthChecked] = useState(false)
  useEffect(() => {
    const token = typeof window !== 'undefined' ? localStorage.getItem('token') : null
    if (!token) { router.replace('/login?next=/create-bot'); return }
    setAuthChecked(true)
  }, [router])
  const [step, setStep] = useState(1)
  const [form, setForm] = useState<FormData>(defaultForm)
  const [chatMessages, setChatMessages] = useState<{ role: string; content: string }[]>([])
  const [chatInput, setChatInput] = useState('')
  const [chatLoading, setChatLoading] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const update = (data: Partial<FormData>) => setForm(prev => ({ ...prev, ...data }))
  const addRoom = () => update({ rooms: [...form.rooms, { name: '', capacity: 2, price: 0, description: '' }] })
  const updateRoom = (i: number, field: keyof Room, value: any) => { const r = [...form.rooms]; r[i] = { ...r[i], [field]: value }; update({ rooms: r }) }
  const removeRoom = (i: number) => update({ rooms: form.rooms.filter((_, idx) => idx !== i) })
  const sendChat = async () => {
    if (!chatInput.trim() || chatLoading) return
    const userMsg = chatInput.trim(); setChatInput('')
    const newMsgs = [...chatMessages, { role: 'user', content: userMsg }]
    setChatMessages(newMsgs); setChatLoading(true)
    try {
      const { data } = await api.post('/preview-chat', { message: userMsg, hotel_data: { name: form.hotelName, description: form.description, address: form.address, phone: form.phone, rooms: form.rooms.filter(r => r.name), communication_style: form.communicationStyle }, history: newMsgs.slice(-8) })
      setChatMessages([...newMsgs, { role: 'assistant', content: data.reply }])
    } catch (e: any) {
      const status = e?.response?.status
      const detail = e?.response?.data?.detail
      const msg = status === 403 || status === 401
        ? 'Сессия истекла. Войди заново.'
        : detail || 'Не удалось связаться с ботом. Попробуй ещё раз.'
      setChatMessages([...newMsgs, { role: 'assistant', content: msg }])
    }
    setChatLoading(false)
  }
  const submitApplication = async () => {
    setSubmitting(true)
    try {
      await api.post('/applications', { hotel_name: form.hotelName, contact_name: form.contactName, contact_phone: form.phone, contact_email: form.email, form_data: { description: form.description, address: form.address, rooms: form.rooms, rules: { checkin: form.checkin, checkout: form.checkout, pets: form.pets, smoking: form.smoking }, amenities: { wifi: form.wifi, parking: form.parking, pool: form.pool, restaurant: form.restaurant, transfer: false, breakfast: form.breakfast }, communication_style: form.communicationStyle } })
      router.push('/success')
    } catch { alert('Error submitting.') }
    setSubmitting(false)
  }
  if (!authChecked) return null
  return (
    <div className="min-h-screen bg-[#0A0A0A]">
      <nav className="bg-[#141414] border-b border-[#262626] px-6 py-4"><div className="max-w-3xl mx-auto flex justify-between items-center"><a href="/" className="text-xl font-bold text-[#3B82F6]">Ex-Machina</a><div className="flex items-center gap-4"><button onClick={() => { setForm(demoForm); setStep(4) }} className="text-xs text-[#737373] hover:text-[#3B82F6] underline">Заполнить демо (Ton Azure)</button><div className="text-sm text-[#A3A3A3]">Step {step} of 4</div></div></div></nav>
      <div className="max-w-3xl mx-auto px-6 mt-6"><div className="flex gap-2">{[1,2,3,4].map(s => (<div key={s} className={`h-2 flex-1 rounded-full ${s <= step ? 'bg-[#3B82F6]' : 'bg-[#262626]'}`} />))}</div></div>
      <div className="max-w-3xl mx-auto px-6 py-8">
        {step === 1 && (<div className="bg-[#141414] rounded-2xl p-8 border border-[#262626]"><h2 className="text-2xl font-bold mb-6 text-[#FAFAFA]">Расскажите о вашем отеле</h2><div className="space-y-4"><div><label className="block text-sm font-medium mb-1 text-[#FAFAFA]">Название отеля *</label><input className="w-full border border-[#262626] bg-[#1A1A1A] text-[#FAFAFA] rounded-lg px-4 py-2 placeholder-[#737373]" value={form.hotelName} onChange={e => update({ hotelName: e.target.value })} placeholder="Тон Азур" /></div><div><label className="block text-sm font-medium mb-1 text-[#FAFAFA]">Адрес</label><input className="w-full border border-[#262626] bg-[#1A1A1A] text-[#FAFAFA] rounded-lg px-4 py-2 placeholder-[#737373]" value={form.address} onChange={e => update({ address: e.target.value })} placeholder="с. Тон, Иссык-Куль" /></div><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm font-medium mb-1 text-[#FAFAFA]">Контактное лицо *</label><input className="w-full border border-[#262626] bg-[#1A1A1A] text-[#FAFAFA] rounded-lg px-4 py-2 placeholder-[#737373]" value={form.contactName} onChange={e => update({ contactName: e.target.value })} placeholder="Бектур" /></div><div><label className="block text-sm font-medium mb-1 text-[#FAFAFA]">Телефон *</label><input className="w-full border border-[#262626] bg-[#1A1A1A] text-[#FAFAFA] rounded-lg px-4 py-2 placeholder-[#737373]" value={form.phone} onChange={e => update({ phone: e.target.value })} placeholder="+996 555 123 456" /></div></div><div><label className="block text-sm font-medium mb-1 text-[#FAFAFA]">Email</label><input className="w-full border border-[#262626] bg-[#1A1A1A] text-[#FAFAFA] rounded-lg px-4 py-2 placeholder-[#737373]" value={form.email} onChange={e => update({ email: e.target.value })} placeholder="hotel@mail.com" /></div><div><label className="block text-sm font-medium mb-1 text-[#FAFAFA]">Описание</label><textarea className="w-full border border-[#262626] bg-[#1A1A1A] text-[#FAFAFA] rounded-lg px-4 py-2 h-24 placeholder-[#737373]" value={form.description} onChange={e => update({ description: e.target.value })} placeholder="Бутик-отель на берегу Иссык-Куля..." /></div></div><div className="mt-6 flex justify-end"><button onClick={() => setStep(2)} disabled={!form.hotelName || !form.phone} className="bg-[#3B82F6] text-white px-6 py-2 rounded-lg disabled:opacity-50 hover:bg-[#2563EB]">Далее</button></div></div>)}
        {step === 2 && (<div className="bg-[#141414] rounded-2xl p-8 border border-[#262626]"><h2 className="text-2xl font-bold mb-6 text-[#FAFAFA]">Номера и цены</h2><div className="space-y-4">{form.rooms.map((room, i) => (<div key={i} className="border border-[#262626] rounded-lg p-4 relative">{form.rooms.length > 1 && <button onClick={() => removeRoom(i)} className="absolute top-2 right-2 text-red-400 hover:text-red-300 text-sm">x</button>}<div className="grid grid-cols-3 gap-3 mb-3"><div><label className="block text-xs text-[#A3A3A3] mb-1">Название</label><input className="w-full border border-[#262626] bg-[#1A1A1A] text-[#FAFAFA] rounded px-3 py-1.5 text-sm placeholder-[#737373]" value={room.name} onChange={e => updateRoom(i, 'name', e.target.value)} placeholder="Twin/Double" /></div><div><label className="block text-xs text-[#A3A3A3] mb-1">Вместимость</label><input type="number" className="w-full border border-[#262626] bg-[#1A1A1A] text-[#FAFAFA] rounded px-3 py-1.5 text-sm" value={room.capacity} onChange={e => updateRoom(i, 'capacity', +e.target.value)} /></div><div><label className="block text-xs text-[#A3A3A3] mb-1">Цена (сом/сутки)</label><input type="number" className="w-full border border-[#262626] bg-[#1A1A1A] text-[#FAFAFA] rounded px-3 py-1.5 text-sm" value={room.price} onChange={e => updateRoom(i, 'price', +e.target.value)} /></div></div><input className="w-full border border-[#262626] bg-[#1A1A1A] text-[#FAFAFA] rounded px-3 py-1.5 text-sm placeholder-[#737373]" value={room.description} onChange={e => updateRoom(i, 'description', e.target.value)} placeholder="Описание" /></div>))}<button onClick={addRoom} className="text-[#3B82F6] text-sm hover:underline">+ Добавить категорию</button></div><div className="mt-6 flex justify-between"><button onClick={() => setStep(1)} className="text-[#A3A3A3]">Назад</button><button onClick={() => setStep(3)} className="bg-[#3B82F6] text-white px-6 py-2 rounded-lg hover:bg-[#2563EB]">Далее</button></div></div>)}
        {step === 3 && (<div className="bg-[#141414] rounded-2xl p-8 border border-[#262626]"><h2 className="text-2xl font-bold mb-6 text-[#FAFAFA]">Правила и услуги</h2><div className="space-y-4"><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm font-medium mb-1 text-[#FAFAFA]">Заезд</label><input className="w-full border border-[#262626] bg-[#1A1A1A] text-[#FAFAFA] rounded-lg px-4 py-2" value={form.checkin} onChange={e => update({ checkin: e.target.value })} /></div><div><label className="block text-sm font-medium mb-1 text-[#FAFAFA]">Выезд</label><input className="w-full border border-[#262626] bg-[#1A1A1A] text-[#FAFAFA] rounded-lg px-4 py-2" value={form.checkout} onChange={e => update({ checkout: e.target.value })} /></div></div><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm font-medium mb-1 text-[#FAFAFA]">Животные</label><select className="w-full border border-[#262626] bg-[#1A1A1A] text-[#FAFAFA] rounded-lg px-4 py-2" value={form.pets} onChange={e => update({ pets: e.target.value })}><option value="no">Нет</option><option value="yes">Да</option><option value="ask">По запросу</option></select></div><div><label className="block text-sm font-medium mb-1 text-[#FAFAFA]">Курение</label><select className="w-full border border-[#262626] bg-[#1A1A1A] text-[#FAFAFA] rounded-lg px-4 py-2" value={form.smoking} onChange={e => update({ smoking: e.target.value })}><option value="no">Нет</option><option value="balcony">На балконе</option><option value="yes">Да</option></select></div></div><div><label className="block text-sm font-medium mb-3 text-[#FAFAFA]">Удобства</label><div className="grid grid-cols-3 gap-2">{[{k:'wifi',l:'Wi-Fi'},{k:'parking',l:'Парковка'},{k:'pool',l:'Бассейн'},{k:'restaurant',l:'Ресторан'},{k:'transfer',l:'Трансфер'},{k:'breakfast',l:'Завтрак'}].map(a => (<label key={a.k} className="flex items-center gap-2 text-sm text-[#FAFAFA]"><input type="checkbox" checked={(form as any)[a.k]} onChange={e => update({ [a.k]: e.target.checked } as any)} className="rounded" />{a.l}</label>))}</div></div><div><label className="block text-sm font-medium mb-1 text-[#FAFAFA]">Стиль бота</label><select className="w-full border border-[#262626] bg-[#1A1A1A] text-[#FAFAFA] rounded-lg px-4 py-2" value={form.communicationStyle} onChange={e => update({ communicationStyle: e.target.value })}><option value="friendly">Дружелюбный</option><option value="formal">Деловой</option><option value="neutral">Нейтральный</option></select></div></div><div className="mt-6 flex justify-between"><button onClick={() => setStep(2)} className="text-[#A3A3A3]">Назад</button><button onClick={() => setStep(4)} className="bg-[#3B82F6] text-white px-6 py-2 rounded-lg hover:bg-[#2563EB]">Тест бота</button></div></div>)}
        {step === 4 && (<div className="bg-[#141414] rounded-2xl p-8 border border-[#262626]"><h2 className="text-2xl font-bold mb-2 text-[#FAFAFA]">Протестируйте бота</h2><p className="text-[#A3A3A3] text-sm mb-6">Напишите вопрос как гость — бот ответит на основе данных вашего отеля.</p><div className="border border-[#262626] rounded-xl h-80 flex flex-col"><div className="flex-1 overflow-y-auto p-4 space-y-3">{chatMessages.length === 0 && <div className="text-center text-[#737373] mt-20 text-sm">Напишите: Сколько стоит номер?</div>}{chatMessages.map((msg, i) => (<div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[75%] rounded-xl px-4 py-2 text-sm whitespace-pre-wrap ${msg.role === 'user' ? 'bg-[#3B82F6] text-white' : 'bg-[#1A1A1A] text-[#FAFAFA]'}`}>{msg.content}</div></div>))}{chatLoading && <div className="flex justify-start"><div className="bg-[#1A1A1A] rounded-xl px-4 py-2 text-sm text-[#737373] animate-pulse">Печатает...</div></div>}</div><div className="border-t border-[#262626] p-3 flex gap-2"><input className="flex-1 border border-[#262626] bg-[#1A1A1A] text-[#FAFAFA] rounded-lg px-3 py-2 text-sm placeholder-[#737373]" value={chatInput} onChange={e => setChatInput(e.target.value)} onKeyDown={e => e.key === 'Enter' && sendChat()} placeholder="Введите сообщение..." /><button onClick={sendChat} disabled={chatLoading} className="bg-[#3B82F6] text-white px-4 py-2 rounded-lg text-sm disabled:opacity-50">Send</button></div></div><div className="mt-6 flex justify-between"><button onClick={() => setStep(3)} className="text-[#A3A3A3]">Назад</button><button onClick={submitApplication} disabled={submitting} className="bg-green-600 text-white px-6 py-2 rounded-lg hover:bg-green-700 disabled:opacity-50">{submitting ? 'Отправка...' : 'Отправить заявку'}</button></div></div>)}
      </div>
    </div>
  )
}
